//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalContractDetail
    {
        public string RentalContractId { get; set; }
        public string StaffId { get; set; }
        public string CustomerId { get; set; }
        public Nullable<bool> Validated { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RentalContract RentalContract { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
